services:

######## USERS SERVICES ##############

  users-manager:
    build:
      context: ./Users/UsersManager
    container_name: users_manager_container
    networks:
      - network-dapr
    ports:
      - "3003:3003"
      - "3502:3502"
    environment:
      - DAPR_APP_ID=usersManager
      - DAPR_APP_PORT=3502

  users-engine:
    build:
      context: ./Users/UsersEngine
    container_name: users_engine_container
    networks:
      - network-dapr
    ports:
      - "3002:3002"
      - "3501:3501"
    environment:
      - DAPR_APP_ID=usersEngine
      - DAPR_APP_PORT=3501

  users-accessor:
    build:
      context: ./Users/UsersAcssesor
    container_name: users_accessor_container
    networks:
      - network-dapr
    ports:
      - "3001:3001"
      - "3500:3500"
    environment:
      - DAPR_APP_ID=usersAccessor
      - DAPR_APP_PORT=3500

  users-manager-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "usersManager", "-app-port", "3003", "-dapr-http-port", "3502"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - users-manager
    networks:
     - network-dapr  

  users-engine-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "usersEngine", "-app-port", "3002", "-dapr-http-port", "3501"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - users-engine
    networks:
     - network-dapr

  users-accessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "usersAccessor", "-app-port", "3001", "-dapr-http-port", "3500"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - mongodb
    network_mode: "service:users-accessor"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - network-dapr

########### NEWS SERVICES##################
  news-manager:
    build:
      context: ./News/NewsManager
    container_name: news_manager_container
    networks:
      - network-dapr
    ports:
      - "3022:3022"
      - "3522:3522"
    environment:
      - DAPR_APP_ID=newsManager
      - DAPR_APP_PORT=3522

  news-accessor:
    build:
      context: ./News/NewsAcssesor
    container_name: news_accessor_container
    networks:
      - network-dapr
    ports:
      - "3020:3020"
      - "3520:3520"
    environment:
      - DAPR_APP_ID=newsAccessor
      - DAPR_APP_PORT=3520
    depends_on:
      - rabbitmq

  news-manager-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "newsManager", "-app-port", "3022", "-dapr-http-port", "3522"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - news-manager
    network_mode: "service:news-manager"  


  news-accessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "newsAccessor", "-app-port", "3020", "-dapr-http-port", "3520"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - news-accessor
    network_mode: "service:news-accessor"

  ########## AI SERVICES ##############
  ai-engine:
    build:
      context: ./AI/AIEngine
    container_name: ai_engine_container
    networks:
      - network-dapr
    ports:
      - "3052:3052"
      - "3551:3551"
    environment:
      - DAPR_APP_ID=aiEngine
      - DAPR_APP_PORT=3551
    depends_on:
      - rabbitmq

  ai-accessor:
    build:
      context: ./AI/AIAcssesor
    container_name: ai_accessor_container
    networks:
      - network-dapr
    ports:
      - "3042:3042"
      - "3541:3541"
    environment:
      - DAPR_APP_ID=aiAcssesor
      - DAPR_APP_PORT=3541
    depends_on:
      - rabbitmq

  ai-engine-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "aiEngine", "-app-port", "3052", "-dapr-http-port", "3551"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - ai-engine
    network_mode: "service:ai-engine" 

  ai-accessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "aiAcssesor", "-app-port", "3042", "-dapr-http-port", "3541"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - ai-accessor
    network_mode: "service:ai-accessor"
  # ######## EMAIL SERVICES ##############
  email-engine:
    build:
      context: ./Email/EmailEngine
    container_name: email_engine_container
    networks:
      - network-dapr
    ports:
      - "3031:3031"
      - "3531:3531"
    environment:
      - DAPR_APP_ID=emailEngine
      - DAPR_APP_PORT=3531
    depends_on:
      - rabbitmq

  email-accessor:
    build:
      context: ./Email/EmialAcssesor
    container_name: email_accessor_container
    networks:
      - network-dapr
    ports:
      - "3032:3032"
      - "3532:3532"
    environment:
      - DAPR_APP_ID=emailAccessor
      - DAPR_APP_PORT=3532
    depends_on:
      - rabbitmq

  email-engine-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "emailEngine", "-app-port", "3031", "-dapr-http-port", "3531"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - email-engine
    network_mode: "service:email-engine" 

  email-accessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd", "-app-id", "emailAccessor", "-app-port", "3032", "-dapr-http-port", "3532"]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - email-accessor
    network_mode: "service:email-accessor"

 
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network-dapr 
networks:
  network-dapr:
   






