# Use the official Node.js image as the base image
FROM node:18
# Set the working directory inside the container
WORKDIR /app
# COPY node_modules/sqlite3 /node_modules/sqlite3

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

COPY  node_modules ./ 
# Install dependencies


# Copy the rest of the application code to the working directory
COPY . .

# Expose the application port
EXPOSE 3001

# Define the command to run the application
CMD ["node", "app.js"]

